/* Generated By:JavaCC: Do not edit this line. Parser.java */
package primula.api.core.assh;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;

import primula.api.core.assh.operator.Converter;
import primula.api.core.assh.operator.FieldOperator;
import primula.api.core.assh.operator.InstanceCreator;
import primula.api.core.assh.operator.MethodOperator;

public class Parser extends Thread implements ParserConstants {
	private boolean requestStop = false;
	static boolean terminal_flg = false;//SphereTerminalが動いているかのフラグ
	static ShellEnvironment shellEnv = ShellEnvironment.getInstance();
	static Parser parser = null;
	static Boolean first = true;

	public Parser() {
	}

	public void run() {
		//ShellEnvironment shellEnv = ShellEnvironment.getInstance();
		//Parser parser = null;
		BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
		String line = null;
		//Boolean first = true;
		ClassTable classTable = new ClassTable();
		while (requestStop == false) {
			System.out.print(shellEnv.getInputLineText());
			System.out.flush();
			if (!terminal_flg) {//コンソールを使用しているとき
				//ここから
				try {
					line = reader.readLine();
				} catch (IOException e) {

				}
				//ここまで}
				//以上に関しては、eclipseのコンソールに表示させる場合
			} else {//Terminalを使用しているとき

				//ここから
				while (true) {
					line = MainPanel.getText();
					if (MainPanel.flg) {
						MainPanel.textField.setText("");
						System.out.println(shellEnv.getDirectory() + '>' + line);//とりあえず
						MainPanel.autoscroll();
						//MainPanel.java内からあるOutputTextAreaでoutが書き変えられている(System.setOut()を利用)
						if (line.length() != 0)
							History.add(line);
						MainPanel.flg = false;
						break;
					} else {
						MainPanel.flg = false;
					}
					if (!terminal_flg) {//追加部分（中平）
						break;
					}
				}
				//ここまで
				//MainPanel.javaを利用したTterminalに表示させる場合
			}
			if (first) {
				parser = new Parser(new StringReader(line));
				first = false;
			} else {
				parser.ReInit(new StringReader(line));
			}

			try {
				if (one_line(shellEnv)) {
					System.out.println("finish!");
					return;
				}
			} catch (Exception e) {
				System.out.println("NOK.");
				System.out.println(e.getMessage());
			} catch (Error e) {
				System.out.println("Oops.");
				System.out.println(e.getMessage());
				break;
			}
			if (terminal_flg) {
				MainPanel.autoscroll();
			}
		}
	}

	static public void parser_AgentWeb(String command) {
		if (first) {
			parser = new Parser(new StringReader(command));
			first = false;
		} else {
			parser.ReInit(new StringReader(command));
		}

		try {
			if (one_line(shellEnv)) {
				System.out.println("finish!");
				return;
			}
		} catch (Exception e) {
			System.out.println("NOK.");
			System.out.println(e.getMessage());
		} catch (Error e) {
			System.out.println("Oops.");
			System.out.println(e.getMessage());
		}
		if (terminal_flg) {
			MainPanel.autoscroll();
		}
	}

	public void requestStop() {
		this.requestStop = true;
	}

	static final public boolean one_line(ShellEnvironment shellEnv) throws ParseException {
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case 0:
			jj_consume_token(0); {
			if (true)
				return false;
		}
			break;
		case VARIABLE:
		case CLASS:
		case NAME:
			commandUnit(shellEnv); {
			if (true)
				return false;
		}
			break;
		default:
			jj_la1[0] = jj_gen;
			jj_consume_token(-1);
			throw new ParseException();
		}
		throw new Error("Missing return statement in function");
	}

	static final public void commandUnit(ShellEnvironment shellEnv) throws ParseException {
		String variable = null;
		List<Object> data = null;
		Object instance = null;
		Class clazz = null;
		int index = -1;
		Token t = null;
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case NAME:
			data = invokecommand(false);
			break;
		case VARIABLE:
		case CLASS:
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case VARIABLE:
				t = jj_consume_token(VARIABLE);
				break;
			case CLASS:
				t = jj_consume_token(CLASS);
				break;
			default:
				jj_la1[1] = jj_gen;
				jj_consume_token(-1);
				throw new ParseException();
			}
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case 15:
				jj_consume_token(15);
				index = getIndex();
				jj_consume_token(16);
				break;
			default:
				jj_la1[2] = jj_gen;
				;
			}
			if (VariableTable.containsKey(t.image)) {
				instance = VariableTable.getOneData(t.image, index);
			} else if (ClassTable.isClass(t.image)) {
				clazz = ClassTable.getClass(t.image);
			}
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case 0:
				jj_consume_token(0);
				if (VariableTable.containsKey(t.image)) {
					if (index > -1) {
						System.out.println(VariableTable.getOneData(t.image, index));
					} else {
						for (Object s : VariableTable.getData(t.image)) {
							System.out.println(s);
						}
					}
				}
				break;
			case 17:
				jj_consume_token(17);
				variable = t.image;
				data = new ArrayList();
				if (jj_2_1(3)) {
					data = invokecommand(true);
				} else {
					switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
					case CONSTANT:
					case NEW:
					case VARIABLE:
					case CLASS:
					case NAME:
						getArgList(data);
						break;
					default:
						jj_la1[3] = jj_gen;
						jj_consume_token(-1);
						throw new ParseException();
					}
				}
				jj_consume_token(0);
				if (!data.isEmpty())
					VariableTable.setVariable(variable, data);
				break;
			default:
				jj_la1[4] = jj_gen;
				invoker(instance, clazz);
			}
			break;
		default:
			jj_la1[5] = jj_gen;
			jj_consume_token(-1);
			throw new ParseException();
		}
	}

	static final public String AmbiguousName() throws ParseException {
		Token t;
		StringBuffer s;
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case NAME:
			t = jj_consume_token(NAME);
			break;
		case CLASS:
			t = jj_consume_token(CLASS);
			break;
		default:
			jj_la1[6] = jj_gen;
			jj_consume_token(-1);
			throw new ParseException();
		}
		s = new StringBuffer(t.image);
		label_1: while (true) {
			if (getToken(1).image.equals(".")) {
				;
			} else {
				break label_1;
			}
			jj_consume_token(18);
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case CLASS:
				t = jj_consume_token(CLASS);
				break;
			case NAME:
				t = jj_consume_token(NAME);
				break;
			case AGENT:
				t = jj_consume_token(AGENT);
				break;
			default:
				jj_la1[7] = jj_gen;
				jj_consume_token(-1);
				throw new ParseException();
			}
			s.append("." + t.image);
		}
		System.out.println(s.toString());
		{
			if (true)
				return s.toString();
		}
		throw new Error("Missing return statement in function");
	}

	static final public void invoker(Object instance, Class clazz) throws ParseException {
		Object result = null;
		label_2: while (true) {
			if (jj_2_2(1)) {
				;
			} else {
				break label_2;
			}
			if (getToken(3).image.equals("(")) {
				result = invokeMethod(instance, clazz);
				System.out.println(result);
			} else if (!getToken(3).image.equals("=")) {
				instance = getFieldValue(instance, clazz);
			} else {
				jj_consume_token(-1);
				throw new ParseException();
			}
		}
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case 18:
			changeFieldValue(instance, clazz);
			break;
		default:
			jj_la1[8] = jj_gen;
			;
		}
	}

	// �?��したインスタンスの持つフィールド�?値を変更する.
	static final public void changeFieldValue(Object instance, Class staticClass) throws ParseException {
		Token t = null;
		String arg = null;
		Object newVal = null;
		Class clazz = null;
		int index = -1;
		jj_consume_token(18);
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case NAME:
			t = jj_consume_token(NAME);
			break;
		case CLASS:
			t = jj_consume_token(CLASS);
			break;
		default:
			jj_la1[9] = jj_gen;
			jj_consume_token(-1);
			throw new ParseException();
		}
		jj_consume_token(17);
		arg = t.image;
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case NEW:
			jj_consume_token(NEW);
			newVal = createNewInstance();
			break;
		case CLASS:
			t = jj_consume_token(CLASS);
			clazz = ClassTable.getClass(t.image);
			break;
		case VARIABLE:
			t = jj_consume_token(VARIABLE);
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case 15:
				jj_consume_token(15);
				index = getIndex();
				jj_consume_token(16);
				break;
			default:
				jj_la1[10] = jj_gen;
				;
			}
			newVal = VariableTable.getOneData(t.image, index);
			break;
		case CONSTANT:
		case NAME:
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case NAME:
				t = jj_consume_token(NAME);
				break;
			case CONSTANT:
				t = jj_consume_token(CONSTANT);
				break;
			default:
				jj_la1[11] = jj_gen;
				jj_consume_token(-1);
				throw new ParseException();
			}
			newVal = Converter.valueTypeConverter(t.image);
			break;
		default:
			jj_la1[12] = jj_gen;
			jj_consume_token(-1);
			throw new ParseException();
		}
		label_3: while (true) {
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case 18:
				;
				break;
			default:
				jj_la1[13] = jj_gen;
				break label_3;
			}
			if (jj_2_3(3)) {
				newVal = getFieldValue(newVal, clazz);
			} else {
				switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
				case 18:
					newVal = invokeMethod(newVal, clazz);
					break;
				default:
					jj_la1[14] = jj_gen;
					jj_consume_token(-1);
					throw new ParseException();
				}
			}
		}
		FieldOperator.changeFieldValue(instance, staticClass, arg, newVal);
	}

	// メソ�?���?��ンストラクタの持つ引数の値を取得す�?
	static final public void getArgList(List<Object> argList) throws ParseException {
		Token t = null;
		Object arg = null;
		Class clazz = null;
		int index = -1;
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case NEW:
			jj_consume_token(NEW);
			arg = createNewInstance();
			break;
		case CLASS:
			t = jj_consume_token(CLASS);
			clazz = ClassTable.getClass(t.image);
			break;
		case VARIABLE:
			t = jj_consume_token(VARIABLE);
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case 15:
				jj_consume_token(15);
				index = getIndex();
				jj_consume_token(16);
				break;
			default:
				jj_la1[15] = jj_gen;
				;
			}
			arg = VariableTable.getOneData(t.image, index);
			break;
		case CONSTANT:
		case NAME:
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case NAME:
				t = jj_consume_token(NAME);
				break;
			case CONSTANT:
				t = jj_consume_token(CONSTANT);
				break;
			default:
				jj_la1[16] = jj_gen;
				jj_consume_token(-1);
				throw new ParseException();
			}
			arg = Converter.valueTypeConverter(t.image);
			break;
		default:
			jj_la1[17] = jj_gen;
			jj_consume_token(-1);
			throw new ParseException();
		}
		label_4: while (true) {
			if (jj_2_4(1)) {
				;
			} else {
				break label_4;
			}
			if (getToken(3).image.equals("(")) {
				arg = invokeMethod(arg, clazz);
			} else {
				switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
				case 18:
					arg = getFieldValue(arg, clazz);
					break;
				default:
					jj_la1[18] = jj_gen;
					jj_consume_token(-1);
					throw new ParseException();
				}
			}
		}
		argList.add(arg);
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case 19:
			jj_consume_token(19);
			getArgList(argList);
			break;
		default:
			jj_la1[19] = jj_gen;
			;
		}
	}

	// �?��したインスタンスの持つフィールド�?値を取得す�?
	static final public Object getFieldValue(Object instance, Class clazz) throws ParseException {
		Token t = null;
		jj_consume_token(18);
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case NAME:
			t = jj_consume_token(NAME);
			break;
		case CLASS:
			t = jj_consume_token(CLASS);
			break;
		default:
			jj_la1[20] = jj_gen;
			jj_consume_token(-1);
			throw new ParseException();
		}
		{
			if (true)
				return FieldOperator.getFieldValue(instance, clazz, t.image);
		}
		throw new Error("Missing return statement in function");
	}

	// �?��したインスタンスの持つメソ�?��を実行す�?
	static final public Object invokeMethod(Object instance, Class clazz) throws ParseException {
		Token t = null;
		List<Object> argList = new ArrayList();
		Object obj = null;
		jj_consume_token(18);
		t = jj_consume_token(NAME);
		jj_consume_token(20);
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case CONSTANT:
		case NEW:
		case VARIABLE:
		case CLASS:
		case NAME:
			getArgList(argList);
			break;
		default:
			jj_la1[21] = jj_gen;
			;
		}
		jj_consume_token(21);
		//System.out.println(instance + " ***** " + clazz + " ***** " + t.image + " ***** " + argList);/////////////////////
		obj = MethodOperator.invokeMethod(instance, clazz, t.image, argList);
		{
			if (true)
				return obj;
		}
		throw new Error("Missing return statement in function");
	}

	// 新たなインスタンスを作�?する.
	static final public Object createNewInstance() throws ParseException {
		Token t = null;
		String str = null;
		List<Object> argList = new ArrayList();
		str = AmbiguousName();
		jj_consume_token(20);
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case CONSTANT:
		case NEW:
		case VARIABLE:
		case CLASS:
		case NAME:
			getArgList(argList);
			break;
		default:
			jj_la1[22] = jj_gen;
			;
		}
		jj_consume_token(21);
		{
			if (true)
				return InstanceCreator.createNewInstance(str, argList);
		}
		throw new Error("Missing return statement in function");
	}

	// コマンド�?実�?
	static final public List<Object> invokecommand(boolean doReturn) throws ParseException {
		Token t = null;
		String cmd = null;
		String fileName = null;
		List<String> fileNames = new ArrayList();
		Object instance = null;
		List<String> option = new ArrayList();
		List<Object> returnValue = new ArrayList();
		int index = -1;
		t = jj_consume_token(NAME);
		cmd = t.image;
		label_5: while (true) {
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case CONSTANT:
			case OPTION:
			case VARIABLE:
			case AGENT:
			case CLASS:
			case NAME:
			case 18:
				;
				break;
			default:
				jj_la1[23] = jj_gen;
				break label_5;
			}
			switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
			case OPTION:
				t = jj_consume_token(OPTION);
				option.add(t.image);
				break;
			case CONSTANT:
				t = jj_consume_token(CONSTANT);
				fileNames.add(t.image);
				break;
			case CLASS:
			case NAME:
			case 18:
				fileName = getFileName();
				fileNames.add(fileName);
				break;
			case AGENT:
				t = jj_consume_token(AGENT);
				instance = t.image;
				break;
			case VARIABLE:
				t = jj_consume_token(VARIABLE);
				switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
				case 15:
					jj_consume_token(15);
					index = getIndex();
					jj_consume_token(16);
					break;
				default:
					jj_la1[24] = jj_gen;
					;
				}
				instance = VariableTable.getOneData(t.image, index);
				label_6: while (true) {
					if (jj_2_5(2)) {
						;
					} else {
						break label_6;
					}
					instance = getFieldValue(instance, null);
				}
				break;
			default:
				jj_la1[25] = jj_gen;
				jj_consume_token(-1);
				throw new ParseException();
			}
		}
		System.out.println(cmd + " " + option + " " + fileNames + " " + instance);////////////////
		returnValue = CommandInvoker.invokeCommand(cmd, option, fileNames, instance);
		if (doReturn) {
			if (true)
				return returnValue;
		} else {
			if (true)
				return null;
		}
		throw new Error("Missing return statement in function");
	}

	// ファイルの名前を取得す�?
	static final public String getFileName() throws ParseException {
		Token t = null;
		StringBuffer s;
		switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
		case NAME:
			t = jj_consume_token(NAME);
			break;
		case CLASS:
			t = jj_consume_token(CLASS);
			break;
		case 18:
			t = jj_consume_token(18);
			break;
		default:
			jj_la1[26] = jj_gen;
			jj_consume_token(-1);
			throw new ParseException();
		}
		s = new StringBuffer(t.image);
		label_7: while (true) {
			if (jj_2_6(1)) {
				;
			} else {
				break label_7;
			}
			if (getToken(1).image.equals(".")) {
				jj_consume_token(18);
				switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
				case CLASS:
					t = jj_consume_token(CLASS);
					break;
				case NAME:
					t = jj_consume_token(NAME);
					break;
				case DIVIDE:
					t = jj_consume_token(DIVIDE);
					break;
				default:
					jj_la1[27] = jj_gen;
					jj_consume_token(-1);
					throw new ParseException();
				}
				s.append("." + t.image);
			} else if (getToken(1).image.equals("\u005c\u005c")) {
				jj_consume_token(22);
				switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
				case CLASS:
					t = jj_consume_token(CLASS);
					break;
				case NAME:
					t = jj_consume_token(NAME);
					break;
				default:
					jj_la1[28] = jj_gen;
					jj_consume_token(-1);
					throw new ParseException();
				}
				s.append("\u005c\u005c" + t.image);
			} else {
				jj_consume_token(-1);
				throw new ParseException();
			}
		}
		//    System.out.println(s.toString());
		{
			if (true)
				return s.toString();
		}
		throw new Error("Missing return statement in function");
	}

	static final public int getIndex() throws ParseException {
		int index = 0;
		Token t = null;
		t = jj_consume_token(CONSTANT);
		index = Integer.parseInt(t.image);
		{
			if (true)
				return index;
		}
		throw new Error("Missing return statement in function");
	}

	static private boolean jj_2_1(int xla) {
		jj_la = xla;
		jj_lastpos = jj_scanpos = token;
		try {
			return !jj_3_1();
		} catch (LookaheadSuccess ls) {
			return true;
		} finally {
			jj_save(0, xla);
		}
	}

	static private boolean jj_2_2(int xla) {
		jj_la = xla;
		jj_lastpos = jj_scanpos = token;
		try {
			return !jj_3_2();
		} catch (LookaheadSuccess ls) {
			return true;
		} finally {
			jj_save(1, xla);
		}
	}

	static private boolean jj_2_3(int xla) {
		jj_la = xla;
		jj_lastpos = jj_scanpos = token;
		try {
			return !jj_3_3();
		} catch (LookaheadSuccess ls) {
			return true;
		} finally {
			jj_save(2, xla);
		}
	}

	static private boolean jj_2_4(int xla) {
		jj_la = xla;
		jj_lastpos = jj_scanpos = token;
		try {
			return !jj_3_4();
		} catch (LookaheadSuccess ls) {
			return true;
		} finally {
			jj_save(3, xla);
		}
	}

	static private boolean jj_2_5(int xla) {
		jj_la = xla;
		jj_lastpos = jj_scanpos = token;
		try {
			return !jj_3_5();
		} catch (LookaheadSuccess ls) {
			return true;
		} finally {
			jj_save(4, xla);
		}
	}

	static private boolean jj_2_6(int xla) {
		jj_la = xla;
		jj_lastpos = jj_scanpos = token;
		try {
			return !jj_3_6();
		} catch (LookaheadSuccess ls) {
			return true;
		} finally {
			jj_save(5, xla);
		}
	}

	static private boolean jj_3_1() {
		if (jj_3R_8())
			return true;
		return false;
	}

	static private boolean jj_3R_13() {
		if (jj_3R_11())
			return true;
		return false;
	}

	static private boolean jj_3_4() {
		Token xsp;
		xsp = jj_scanpos;
		jj_lookingAhead = true;
		jj_semLA = getToken(3).image.equals("(");
		jj_lookingAhead = false;
		if (!jj_semLA || jj_3R_12()) {
			jj_scanpos = xsp;
			if (jj_3R_13())
				return true;
		}
		return false;
	}

	static private boolean jj_3R_12() {
		if (jj_3R_17())
			return true;
		return false;
	}

	static private boolean jj_3R_15() {
		if (jj_scan_token(22))
			return true;
		return false;
	}

	static private boolean jj_3R_24() {
		if (jj_scan_token(15))
			return true;
		return false;
	}

	static private boolean jj_3_6() {
		Token xsp;
		xsp = jj_scanpos;
		jj_lookingAhead = true;
		jj_semLA = getToken(1).image.equals(".");
		jj_lookingAhead = false;
		if (!jj_semLA || jj_3R_14()) {
			jj_scanpos = xsp;
			jj_lookingAhead = true;
			jj_semLA = getToken(1).image.equals("\u005c\u005c");
			jj_lookingAhead = false;
			if (!jj_semLA || jj_3R_15())
				return true;
		}
		return false;
	}

	static private boolean jj_3R_14() {
		if (jj_scan_token(18))
			return true;
		return false;
	}

	static private boolean jj_3R_10() {
		if (jj_3R_11())
			return true;
		return false;
	}

	static private boolean jj_3R_23() {
		Token xsp;
		xsp = jj_scanpos;
		if (jj_scan_token(14)) {
			jj_scanpos = xsp;
			if (jj_scan_token(13)) {
				jj_scanpos = xsp;
				if (jj_scan_token(18))
					return true;
			}
		}
		while (true) {
			xsp = jj_scanpos;
			if (jj_3_6()) {
				jj_scanpos = xsp;
				break;
			}
		}
		return false;
	}

	static private boolean jj_3R_9() {
		if (jj_3R_17())
			return true;
		return false;
	}

	static private boolean jj_3_2() {
		Token xsp;
		xsp = jj_scanpos;
		jj_lookingAhead = true;
		jj_semLA = getToken(3).image.equals("(");
		jj_lookingAhead = false;
		if (!jj_semLA || jj_3R_9()) {
			jj_scanpos = xsp;
			jj_lookingAhead = true;
			jj_semLA = !getToken(3).image.equals("=");
			jj_lookingAhead = false;
			if (!jj_semLA || jj_3R_10())
				return true;
		}
		return false;
	}

	static private boolean jj_3_5() {
		if (jj_3R_11())
			return true;
		return false;
	}

	static private boolean jj_3R_17() {
		if (jj_scan_token(18))
			return true;
		return false;
	}

	static private boolean jj_3R_22() {
		if (jj_scan_token(VARIABLE))
			return true;
		Token xsp;
		xsp = jj_scanpos;
		if (jj_3R_24())
			jj_scanpos = xsp;
		while (true) {
			xsp = jj_scanpos;
			if (jj_3_5()) {
				jj_scanpos = xsp;
				break;
			}
		}
		return false;
	}

	static private boolean jj_3R_21() {
		if (jj_scan_token(AGENT))
			return true;
		return false;
	}

	static private boolean jj_3R_20() {
		if (jj_3R_23())
			return true;
		return false;
	}

	static private boolean jj_3_3() {
		if (jj_3R_11())
			return true;
		return false;
	}

	static private boolean jj_3R_19() {
		if (jj_scan_token(CONSTANT))
			return true;
		return false;
	}

	static private boolean jj_3R_16() {
		Token xsp;
		xsp = jj_scanpos;
		if (jj_3R_18()) {
			jj_scanpos = xsp;
			if (jj_3R_19()) {
				jj_scanpos = xsp;
				if (jj_3R_20()) {
					jj_scanpos = xsp;
					if (jj_3R_21()) {
						jj_scanpos = xsp;
						if (jj_3R_22())
							return true;
					}
				}
			}
		}
		return false;
	}

	static private boolean jj_3R_18() {
		if (jj_scan_token(OPTION))
			return true;
		return false;
	}

	static private boolean jj_3R_11() {
		if (jj_scan_token(18))
			return true;
		Token xsp;
		xsp = jj_scanpos;
		if (jj_scan_token(14)) {
			jj_scanpos = xsp;
			if (jj_scan_token(13))
				return true;
		}
		return false;
	}

	static private boolean jj_3R_8() {
		if (jj_scan_token(NAME))
			return true;
		Token xsp;
		while (true) {
			xsp = jj_scanpos;
			if (jj_3R_16()) {
				jj_scanpos = xsp;
				break;
			}
		}
		return false;
	}

	static private boolean jj_initialized_once = false;
	/** Generated Token Manager. */
	static public ParserTokenManager token_source;
	static SimpleCharStream jj_input_stream;
	/** Current token. */
	static public Token token;
	/** Next token. */
	static public Token jj_nt;
	static private int jj_ntk;
	static private Token jj_scanpos, jj_lastpos;
	static private int jj_la;
	/** Whether we are looking ahead. */
	static private boolean jj_lookingAhead = false;
	static private boolean jj_semLA;
	static private int jj_gen;
	static final private int[] jj_la1 = new int[29];
	static private int[] jj_la1_0;
	static {
		jj_la1_init_0();
	}

	private static void jj_la1_init_0() {
		jj_la1_0 = new int[] { 0x6801, 0x2800, 0x8000, 0x6a80, 0x20001, 0x6800, 0x6000, 0x7000, 0x40000, 0x6000, 0x8000,
				0x4080, 0x6a80, 0x40000, 0x40000, 0x8000, 0x4080, 0x6a80, 0x40000, 0x80000, 0x6000, 0x6a80, 0x6a80,
				0x47c80, 0x8000, 0x47c80, 0x46000, 0x6040, 0x6000, };
	}

	static final private JJCalls[] jj_2_rtns = new JJCalls[6];
	static private boolean jj_rescan = false;
	static private int jj_gc = 0;

	/** Constructor with InputStream. */
	public Parser(java.io.InputStream stream) {
		this(stream, null);
	}

	/** Constructor with InputStream and supplied encoding */
	public Parser(java.io.InputStream stream, String encoding) {
		if (jj_initialized_once) {
			System.out.println("ERROR: Second call to constructor of static parser.  ");
			System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
			System.out.println("       during parser generation.");
			throw new Error();
		}
		jj_initialized_once = true;
		try {
			jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1);
		} catch (java.io.UnsupportedEncodingException e) {
			throw new RuntimeException(e);
		}
		token_source = new ParserTokenManager(jj_input_stream);
		token = new Token();
		jj_ntk = -1;
		jj_gen = 0;
		for (int i = 0; i < 29; i++)
			jj_la1[i] = -1;
		for (int i = 0; i < jj_2_rtns.length; i++)
			jj_2_rtns[i] = new JJCalls();
	}

	/** Reinitialise. */
	static public void ReInit(java.io.InputStream stream) {
		ReInit(stream, null);
	}

	/** Reinitialise. */
	static public void ReInit(java.io.InputStream stream, String encoding) {
		try {
			jj_input_stream.ReInit(stream, encoding, 1, 1);
		} catch (java.io.UnsupportedEncodingException e) {
			throw new RuntimeException(e);
		}
		token_source.ReInit(jj_input_stream);
		token = new Token();
		jj_ntk = -1;
		jj_gen = 0;
		for (int i = 0; i < 29; i++)
			jj_la1[i] = -1;
		for (int i = 0; i < jj_2_rtns.length; i++)
			jj_2_rtns[i] = new JJCalls();
	}

	/** Constructor. */
	public Parser(java.io.Reader stream) {
		if (jj_initialized_once) {
			System.out.println("ERROR: Second call to constructor of static parser. ");
			System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
			System.out.println("       during parser generation.");
			throw new Error();
		}
		jj_initialized_once = true;
		jj_input_stream = new SimpleCharStream(stream, 1, 1);
		token_source = new ParserTokenManager(jj_input_stream);
		token = new Token();
		jj_ntk = -1;
		jj_gen = 0;
		for (int i = 0; i < 29; i++)
			jj_la1[i] = -1;
		for (int i = 0; i < jj_2_rtns.length; i++)
			jj_2_rtns[i] = new JJCalls();
	}

	/** Reinitialise. */
	static public void ReInit(java.io.Reader stream) {
		jj_input_stream.ReInit(stream, 1, 1);
		token_source.ReInit(jj_input_stream);
		token = new Token();
		jj_ntk = -1;
		jj_gen = 0;
		for (int i = 0; i < 29; i++)
			jj_la1[i] = -1;
		for (int i = 0; i < jj_2_rtns.length; i++)
			jj_2_rtns[i] = new JJCalls();
	}

	/** Constructor with generated Token Manager. */
	public Parser(ParserTokenManager tm) {
		if (jj_initialized_once) {
			System.out.println("ERROR: Second call to constructor of static parser. ");
			System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
			System.out.println("       during parser generation.");
			throw new Error();
		}
		jj_initialized_once = true;
		token_source = tm;
		token = new Token();
		jj_ntk = -1;
		jj_gen = 0;
		for (int i = 0; i < 29; i++)
			jj_la1[i] = -1;
		for (int i = 0; i < jj_2_rtns.length; i++)
			jj_2_rtns[i] = new JJCalls();
	}

	/** Reinitialise. */
	public void ReInit(ParserTokenManager tm) {
		token_source = tm;
		token = new Token();
		jj_ntk = -1;
		jj_gen = 0;
		for (int i = 0; i < 29; i++)
			jj_la1[i] = -1;
		for (int i = 0; i < jj_2_rtns.length; i++)
			jj_2_rtns[i] = new JJCalls();
	}

	static private Token jj_consume_token(int kind) throws ParseException {
		Token oldToken;
		if ((oldToken = token).next != null)
			token = token.next;
		else
			token = token.next = token_source.getNextToken();
		jj_ntk = -1;
		if (token.kind == kind) {
			jj_gen++;
			if (++jj_gc > 100) {
				jj_gc = 0;
				for (int i = 0; i < jj_2_rtns.length; i++) {
					JJCalls c = jj_2_rtns[i];
					while (c != null) {
						if (c.gen < jj_gen)
							c.first = null;
						c = c.next;
					}
				}
			}
			return token;
		}
		token = oldToken;
		jj_kind = kind;
		throw generateParseException();
	}

	static private final class LookaheadSuccess extends java.lang.Error {
	}

	static final private LookaheadSuccess jj_ls = new LookaheadSuccess();

	static private boolean jj_scan_token(int kind) {
		if (jj_scanpos == jj_lastpos) {
			jj_la--;
			if (jj_scanpos.next == null) {
				jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
			} else {
				jj_lastpos = jj_scanpos = jj_scanpos.next;
			}
		} else {
			jj_scanpos = jj_scanpos.next;
		}
		if (jj_rescan) {
			int i = 0;
			Token tok = token;
			while (tok != null && tok != jj_scanpos) {
				i++;
				tok = tok.next;
			}
			if (tok != null)
				jj_add_error_token(kind, i);
		}
		if (jj_scanpos.kind != kind)
			return true;
		if (jj_la == 0 && jj_scanpos == jj_lastpos)
			throw jj_ls;
		return false;
	}

	/** Get the next Token. */
	static final public Token getNextToken() {
		if (token.next != null)
			token = token.next;
		else
			token = token.next = token_source.getNextToken();
		jj_ntk = -1;
		jj_gen++;
		return token;
	}

	/** Get the specific Token. */
	static final public Token getToken(int index) {
		Token t = jj_lookingAhead ? jj_scanpos : token;
		for (int i = 0; i < index; i++) {
			if (t.next != null)
				t = t.next;
			else
				t = t.next = token_source.getNextToken();
		}
		return t;
	}

	static private int jj_ntk() {
		if ((jj_nt = token.next) == null)
			return (jj_ntk = (token.next = token_source.getNextToken()).kind);
		else
			return (jj_ntk = jj_nt.kind);
	}

	static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
	static private int[] jj_expentry;
	static private int jj_kind = -1;
	static private int[] jj_lasttokens = new int[100];
	static private int jj_endpos;

	static private void jj_add_error_token(int kind, int pos) {
		if (pos >= 100)
			return;
		if (pos == jj_endpos + 1) {
			jj_lasttokens[jj_endpos++] = kind;
		} else if (jj_endpos != 0) {
			jj_expentry = new int[jj_endpos];
			for (int i = 0; i < jj_endpos; i++) {
				jj_expentry[i] = jj_lasttokens[i];
			}
			jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
				int[] oldentry = (int[]) (it.next());
				if (oldentry.length == jj_expentry.length) {
					for (int i = 0; i < jj_expentry.length; i++) {
						if (oldentry[i] != jj_expentry[i]) {
							continue jj_entries_loop;
						}
					}
					jj_expentries.add(jj_expentry);
					break jj_entries_loop;
				}
			}
			if (pos != 0)
				jj_lasttokens[(jj_endpos = pos) - 1] = kind;
		}
	}

	/** Generate ParseException. */
	static public ParseException generateParseException() {
		jj_expentries.clear();
		boolean[] la1tokens = new boolean[23];
		if (jj_kind >= 0) {
			la1tokens[jj_kind] = true;
			jj_kind = -1;
		}
		for (int i = 0; i < 29; i++) {
			if (jj_la1[i] == jj_gen) {
				for (int j = 0; j < 32; j++) {
					if ((jj_la1_0[i] & (1 << j)) != 0) {
						la1tokens[j] = true;
					}
				}
			}
		}
		for (int i = 0; i < 23; i++) {
			if (la1tokens[i]) {
				jj_expentry = new int[1];
				jj_expentry[0] = i;
				jj_expentries.add(jj_expentry);
			}
		}
		jj_endpos = 0;
		jj_rescan_token();
		jj_add_error_token(0, 0);
		int[][] exptokseq = new int[jj_expentries.size()][];
		for (int i = 0; i < jj_expentries.size(); i++) {
			exptokseq[i] = jj_expentries.get(i);
		}
		return new ParseException(token, exptokseq, tokenImage);
	}

	/** Enable tracing. */
	static final public void enable_tracing() {
	}

	/** Disable tracing. */
	static final public void disable_tracing() {
	}

	static private void jj_rescan_token() {
		jj_rescan = true;
		for (int i = 0; i < 6; i++) {
			try {
				JJCalls p = jj_2_rtns[i];
				do {
					if (p.gen > jj_gen) {
						jj_la = p.arg;
						jj_lastpos = jj_scanpos = p.first;
						switch (i) {
						case 0:
							jj_3_1();
							break;
						case 1:
							jj_3_2();
							break;
						case 2:
							jj_3_3();
							break;
						case 3:
							jj_3_4();
							break;
						case 4:
							jj_3_5();
							break;
						case 5:
							jj_3_6();
							break;
						}
					}
					p = p.next;
				} while (p != null);
			} catch (LookaheadSuccess ls) {
			}
		}
		jj_rescan = false;
	}

	static private void jj_save(int index, int xla) {
		JJCalls p = jj_2_rtns[index];
		while (p.gen > jj_gen) {
			if (p.next == null) {
				p = p.next = new JJCalls();
				break;
			}
			p = p.next;
		}
		p.gen = jj_gen + xla - jj_la;
		p.first = token;
		p.arg = xla;
	}

	static final class JJCalls {
		int gen;
		Token first;
		int arg;
		JJCalls next;
	}

}
